language: node_js
env:
  global:
    - secure: "fwGPnhZUADCSqN2j6fVBVTqGCzd/Q4zLPQaCazsYCqfJgmKZAdoYfMHqt9XfftyfFW6RwpuM5cv7KJsjbWPUjBvin/SeIZkLS3CCUb61UBqC5Gvw7PUQnZ/ikdHOCpifAt/oznGA46qBDnHmdIG+J4x/33chSbQBYWX/+uxmjwWqWG8U6q847Adjnz5KdlLLfhrQhDDpzZ5GWR3Q+IBkEXjJsOZ0rWr5IDS0XThsX4wrQB3KHC7ng64PkblN/NUdvWV361BwtxguXhFcS9YWJW8ZkY0Y2pAzNhqKBKw/DKpSlog8o06xgYH0ybNJDOA9SgrzQt5HmOFPHvZrUr6fLj/fUuhycnKX5Uhc4eQufR8R6LQbVwwWBpXnRl8Nsltvjmlej3UgHR09l9koysQ53eU2blKlxlEvyJgtkOx88gffCmB6ZrkykZ0auKcEx1taV9GiwPSNPzJgFtI4pjP1I4YLbDKPrgYp5ReDcUnPO7jtaW7zREBjJOfIwGR/ukZkVxSHqGPNeIlqgYLU5+2m4/8wjJFlIVd6f3F0JvVVsyYDI9/hpdPhcJq3qfsVXhQ/IAe6ndOO9FDJh96hhtFMNFncLKs0Q5vmo8+KfifYdtz58JWy7CHQikNHCLmtfjNd/Mz+unr2oi6NxD2zWYL8trl+fc0Dy66W5DohjoiIYQQ="
    - secure: "pgHWTjMXEJq6HFvBV7CX+2Nk02Muc1oqu834lk3K7R2kjx9Mu0YsdTAIpb5qkUrl/bPRXDbK1n05zFQuLWVG6n+sEm2x93p/oe5ifh7UBbL7DYfawg0KQIN6tCYQQy+8OoZ/+j8rq9O59Mk7ZPxvOVEkhdgqxuWDM7ARPiHV/bkApnV1CXU2FthxXgrLx+ZCLY56crhGNIBYwCFURsj4K3nYu/2yF5X0s/A/LvL/TliybRyE5WrKn2Zy8a+XDGapqIGpevLLIZRErwikAVb8B6s9W1vB0HC4JQLUHz5Qvbtodk3BudVOmiQxYGlsKXAEwlAXqemrlgKhGWzkZdI3EdJ7Y71+JfV8aixNrtewZbJgD6m++bqbRK00A8dpVHjiOVSa0WZOTDpr2VocjGTZuvt0SgPM1ZY2PlGjuUfQDBYW6EYWGe00sEbOZNnhLkx00LVjzt05V8dgfx6zu9+1eK49qRiqvZ2a7djm3r++D+uQQmQe2Ra9iukYu5DkND9AT/gRFBNNXvvV35qna3r8ycSc0QhuPFqTPhgt6e0mo5J9vtu+Z3X6cnLfKJGe1FoOKENw+A/zs5QyPQdVNseVVF3PV2NB7r32qgPS4or/Z8urh0JkDIBOeD6llEOIIQAhvQn9v0utreArnUrz4UPn9ZbI6YUqm2k3DJoQO3UzT5o="
before_install:
 - sudo snap install jo
install:
 - npm install
script:
 - npm build
node_js:
- node
after_success:
 - bash travis_build.sh