language: node_js
env:
  global:
    - secure: "DmujPbQK2yyITLSbOKutZxe0WwlEsMaA4GEVoctp9/4Xb9IUAfnWBnq/Q6c4aH8KTVLMqiV8zpv8e/Afqc8AwU3wmBnO8+/xEi45n/mum0ApjtOaZBBUYN5FuTZTmoXXD81YtNWsO+ENiGHZt0AYSNvFRgN1iyZsp3knPRBYxoGaVu8qTwzq388LDD2QfbNFaAv0YK2Ptxsea5NSvEbkBEhimhLCUUmFJELYGkhfsmUXycUIqOUfJqdv9KLjXqrI6Pefy2CrrL1uWbk1hObn/Y1cnP0vj4ymkPHXCNuqPNFaGqffyEHEqQroxaHUF8usO6W+TlPbxx+rslOQ8F17LL09amKty4bWK0shzeLwssHxC+dAPZpPj7yCGJRwKxRBPSjDv+zMbvK7xlBf/YC9Ud6Z5TbvE7klg4/GC72q0FO5kS7tdD/VCNK1LwbLD2E8zpIHc8UR1IkKuArmmKb0FXVa9wwuunB99WSfxBiQfX3n7fw1EcaGW3h5NQxGNqvzmrQG1C8sqpCj6QawNoh25j/LV6gXu0YZnr/iBF/WZn0j7GYaug7UyHzNaNcdw1IO0v2PluOjwhEqUGDpfjs0gnYSt6dr7F0E4tv4Esnv8JvA8UHoK37ghA5AfFImDCyVUaMwRQwrfIfPcP7SDU+O8H0uVMKvvdDlri7NZfzIUb8="
    - secure: "Zx/DpoER3dSnljX+mLmrzgutCD7VDpAuQKdgGtPBUFjp+eyxiQvvtG3Qq24XcDZ+XtWJxW/aWh0KshGE1/UUtylg8l6Cdr1acLDPYpQo8by1Lx8W9wYKC1BphEv0cug6MQEkCnqf4IycPQKgt8ADFVzG/aFKD+8TDOQz9yt1EpSKLDYz+PBME1J83XYKZzRl06nw4TLDB9jdvETQ5ZEymNzWCrV3uVi3cqlt69QoS8+Tm5jy7rnkWLV+A5KznrBxaP4eR7rZFhjNwO74J4xWgIpTZDMcqlKmwLMMPyJculQb17d68BtxQyHfiIp139B6n4PYGf4zDIZnFycVezw2wR8V10WT7VtKtVu6x83/GOKB/naGtw/g9FtMblca23WACvxNZ/8shuW5nefKjqxKQIhS/zV/UGv/2J/z7oYSGiF36aGxu0kOzVXtmyN6NlqngMJeDESpSEJZjI5HSdzHTdEkvQ1iuhFGPZPWBOj6Uj5HOyzQUvnik55UwJfT3+7/NwK59B0InvrDGk00CKDypSoCvZHJArQJK6qvJ6hDPLp6TrnAh8irqj9LxuRcQvoXcSL6DEn/PR1LqPXlZO9HFf2TpF4hXvHfpStWa3Phk0nQl5Crcwn7uM5X3H4MU7KMJP7ftpj6SIZR1kHrjrdyrbNwcbEDqmaE60q/BVV2gOw="
before_install:
 - sudo snap install jo
install:
 - npm install
script:
 - npm run build
node_js:
- node
after_success:
 - bash travis_build.sh